spring:
  application:
    name: MoviesAPI

  datasource:
    username: root
    password: Arun@sql
    url: jdbc:mysql://localhost:3306/movies-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


project:
  poster: posters/